apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt
data:
  secret-key: YzRmMDMwODFlYWRiNDVhZDk4NzIwNGMwYjc2ZTEzZTI2M2U0NzNjY2MxM2I5ZDg0NzdlODQwMjQ5MTgzNTA4ODAxMmZkZDIwNGVkNDVmZDVkNGNjZDJjYThmZDBjMTI3MzBiMTNlYTQ4Zjk4NzJhYTUyMjAzYzcxNDA2MWUyNGU=