apiVersion: v1
kind: Secret
metadata:
  name: jwt-token-key
type: Opaque
data:
  key-jtw: YzRmMDMwODFlYWRiNDVhZDk4NzIwNGMwYjc2ZTEzZTI2M2U0NzNjY2MxM2I5ZDg0NzdlODQwMjQ5MTgzNTA4ODAxMmZkZDIwNGVkNDVmZDVkNGNjZDJjYThmZDBjMTI3MzBiMTNlYTQ4Zjk4NzJhYTUyMjAzYzcxNDA2MWUyNGU=