zuul:
  routes:  
    produto-api:
      path: /produto-api/**
      sensitiveHeaders:
      serviceId: produto-api
eureka:
      instance:
        prefer-ip-address: true
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      host: localhost
          
---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
   