server:
  port: 8761
  
spring:
  application:
      name: eureka-server
eureka:
  instance:
    hostname: discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_DISCOVERY_SERVER:localhost}:${server.port}/eureka/