apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-eureka-client-pv-claim
  labels:
    app: eureka-client
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi