apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-eureka-server-pv-claim
  labels:
    app: eureka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi