apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
  labels:
    app: api-produto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
      - name: api-produto
        image: esgoncalcves/api-produto
        ports:
        - containerPort: 7000
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
        - name: HOST_MYSQL
          value: mysql-service
        - name: DB_USER_APP
          valueFrom:
            secretKeyRef:
              name: eagrobusiness-config-secret
              key: username
        - name: DB_PSW_APP
          valueFrom:
              secretKeyRef:
                name: eagrobusiness-config-secret
                key: password